FROM jbarlow83/ocrmypdf:v16.0.4

RUN apt-get update && apt-get install -y git libgl1-mesa-glx
RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
RUN pip3 install git+https://github.com/ocrmypdf/OCRmyPDF-EasyOCR.git
